services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    networks:
      - langnet
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant/qdrant_data:/qdrant/storage

  langchain-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: langchain_api
    restart: unless-stopped
    networks:
      - langnet
    env_file:
      - ./.env
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    volumes:
      - ./langserver/data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

configs:
  qdrant_config:
    content: |
      log_level: INFO
      storage:
        path: /qdrant/storage

networks:
  langnet:
    driver: bridge
